# Generated by Django 4.1.13 on 2024-12-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritearticle',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favoritearticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_favorite_article'),
        ),
    ]
